site_name: Medical Dispenser Online - Manual de usuario
site_url: https://fagorhealthcare.github.io/fmd-manual/
nav:
  - Inicio: 'index.md'
  - Activación del servicio: '1_activacion.md'
  - Sincronización de categorías: '2_categorias.md'
  - Acceso a la web: '3_acceso_web.md'
copyright: Fagor Halthcare &copy; 2023
theme:
  name: 'material'
  logo: 'images/fagor-medical-dispenser-logo.png'
  features:
    - navigation.instant
    - navigation.footer
extra:
  generator: false
