site_name: Medical Dispenser Online - Manual de usuario
site_url: https://fagorhealthcare.github.io/fmd-manual/
nav:
  - Introducción: 'introduction.md'
  - Capítulo 1: 'chapter1.md'
copyright: Fagor Halthcare &copy; 2023
theme:
  name: 'material'
  logo: 'images/fagor-medical-dispenser-logo.png'
  features:
    - navigation.instant
    - navigation.footer
extra:
  generator: false
