name: Generate MkDocs Documentation and Docker Image

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Pandoc
      uses: docker://pandoc/latex:2.9

    - name: Convert Markdown to PDF
      run: pandoc ./docs/*.md -o documentation.pdf

    - name: Build documentation using MkDocs Action
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        

    # - name: Build Docker image with Nginx
    #   run: docker build -t gailen/fmd-manual:latest .

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: gailen
    #     password: ${{ secrets.GAILEN_DOCKERHUB_PASSWORD }}

    # - name: Push Docker image
    #   run: docker push gailen/fmd-manual:latest
