name: Generate PDF Documentation

on:
  push:
    branches:
      - mainNO

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Convert Markdown to PDF
      run: pandoc ./docs/*.md -o documentation.pdf

    - name: Upload PDF to Releases
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./documentation.pdf
        asset_name: documentation.pdf
        asset_content_type: application/pdf
